pipeline {
    agent any
    tools {
        maven 'maven3.9.8'
    }
    stages {
        stage("build") {
            steps {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage("test") {
            steps {
                echo 'Running Unit Tests on worker app'
                // Add test execution steps here if needed
            }
        }
        stage("package") {
            steps {
                echo 'Packaging worker app'
                dir('worker') {
                    sh 'mvn package'
                }
            }
        }
    }
    post {
        always {
            echo 'Building multibranch pipeline for worker is completed..'
        }
    }
}
