
pipeline {
    agent any
    tools {
        maven 'maven3.9.8'
    }
    stages {
        stage('Build') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Compiling worker app..'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('Test') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Running Unit Tests on worker app..'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('Package') {
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'Packaging worker app..'
                dir('worker') {
                    sh 'mvn package -DskipTests'
                }
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }
    post {
        always {
            echo 'Building multibranch pipeline for worker is completed..'
        }
        failure {
            slackSend(
                channel: "instavote-cd",
                message: ":x: Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
            )
        }
        success {
            slackSend(
                channel: "instavote-cd",
                message: ":white_check_mark: Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
            )
        }
    }
}

